# Generated by Django 2.1.7 on 2019-09-12 06:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Balance', models.DecimalField(decimal_places=3, max_digits=12)),
                ('Authorization_Forms', models.CharField(choices=[('Unchecked', 'Unchecked'), ('Checked', 'Checked')], max_length=20)),
                ('Resellr', models.CharField(choices=[('Unchecked', 'Unchecked'), ('Checked', 'Checked')], max_length=20)),
                ('Client_may_have_Private', models.CharField(choices=[('Unchecked', 'Unchecked'), ('Checked', 'Checked')], max_length=20)),
            ],
        ),
    ]
