# Generated by Django 2.1.7 on 2019-09-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Resellr',
            new_name='Reseller',
        ),
    ]
