# Generated by Django 2.1.7 on 2019-09-12 19:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_APP', '0002_auto_20190912_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
